### ISSUE TITLE
remove console logs

### ISSUE THREAD

**Issue by MorisR** [WebAhead6/Autocomplete#17]
remove console logs ( or only show them when you're in development phase/mode)
https://github.com/WebAhead6/Autocomplete/blob/master/handlers/datafetcher.js#L10
https://github.com/WebAhead6/Autocomplete/blob/master/handlers/datafetcher.js#L22
https://github.com/WebAhead6/Autocomplete/blob/master/handlers/public.js#L18

**Comment by MorisR** [comment]
it's not a must, but it's a better practice to do so

**Comment by abeerrizik** [comment]
Resolved
